version: '3.8'
services:
  dotnet_postgres:
    image: postgres:alpine
    
  dotnet_rabbitmq:
    image: rabbitmq:3-alpine
    
  dotnet_minio:
    image: minio/minio:latest
    
  dotnet_mongodb:
    image: mongo:latest
    
  dotnet_jaeger:
    image: jaegertracing/all-in-one:latest
    
  dotnet_main:
    image: dotnet-web
    
  dotnet_mailing:
    image: dotnet-web
    
  dotnet_storage:
    image: dotnet-web