version: '3.8'
services:
  dotnet_postgres:
    image: postgres:16
    container_name: dotnet-hw-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Dotnet.Homeworks
    ports:
      - "5434:5432"
    volumes:
      - dotnet_postgres_data:/var/lib/postgresql/data
    
  dotnet_rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=fuzikort
      - RABBITMQ_DEFAULT_PASS=fuzikort
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - dotnet_network
    
  dotnet_minio:
    image: minio/minio:latest
    
  dotnet_mongodb:
    image: mongo:latest
    
  dotnet_jaeger:
    image: jaegertracing/all-in-one:latest
    
  dotnet_main:
    image: dotnet-web
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    container_name: dotnet-web
    environment:
      ConnectionStrings__Default: "User ID=postgres;Password=password;Host=localhost;Port=5432;Database=Dotnet.Homeworks"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - dotnet_postgres
    
  dotnet_mailing:
    build:
      context: .
      dockerfile: Dotnet.Homeworks.Mailing.API/Dockerfile
    depends_on:
      - dotnet_rabbitmq
    environment:
      EmailConfig__Email: "fuzikort@yandex.ru"
      EmailConfig__Host: "smtp.yandex.ru"
      EmailConfig__Port: "465"
      EmailConfig__Password: "Gaffarov14/"
      RabbitMqConfig__Username: ""
      RabbitMqConfig__Password: "fuzikort"
      RabbitMqConfig__Hostname: "dotnet_rabbitmq:5672"
    networks:
      - dotnet_network
    
  dotnet_storage:
    image: dotnet-web
  dotnet.homeworks.mainproject:
    image: dotnet.homeworks.mainproject
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile

  dotnet.homeworks.mainproject-1:
    image: dotnet.homeworks.mainproject-1
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
