version: '3.8'
services:
  dotnet_postgres:
    image: postgres:alpine
    container_name: dotnet-hw-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Dotnet.Homeworks
    ports:
      - "5434:5432"
    volumes:
      - dotnet_postgres_data:/var/lib/postgresql/data
    networks:
      - dotnet_network
  
  dotnet_rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: fuzikort
      RABBITMQ_DEFAULT_PASS: fuzikort
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - dotnet_network
  
  dotnet_minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
  
  dotnet_mongodb:
    image: mongo:latest
  
  dotnet_jaeger:
    image: jaegertracing/all-in-one:latest
  
  
  dotnet_main:
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    depends_on:
      - dotnet_postgres
      - dotnet_rabbitmq
    environment:
      ASPNETCORE_URLS: "http://*:80"
      RabbitMqConfig__Username: "fuzikort"
      RabbitMqConfig__Password: "fuzikort"
      RabbitMqConfig__Hostname: "dotnet_rabbitmq:5672"
      ConnectionStrings__Default: "User ID=postgres;Password=password;Host=localhost;Port=5432;Database=Dotnet.Homeworks"
    ports:
      - "9000:80"
    networks:
      - dotnet_network
  
  dotnet_mailing:
    build:
      context: .
      dockerfile: Dotnet.Homeworks.Mailing.API/Dockerfile
    depends_on:
      - dotnet_rabbitmq
    environment:
      EmailConfig__Email: "fuzikort@yandex.ru"
      EmailConfig__Host: "smtp.yandex.ru"
      EmailConfig__Port: "465"
      EmailConfig__Password: "Gaffarov14"
      RabbitMqConfig__Username: "fuzikort"
      RabbitMqConfig__Password: "fuzikort"
      RabbitMqConfig__Hostname: "dotnet_rabbitmq:5672"
    networks:
      - dotnet_network

  dotnet_storage:
    image: dotnet-web-storage
    build:
      context: .
      dockerfile: Dotnet.Homeworks.Storage.API/Dockerfile
    ports:
      - "8082:8082"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:8082
      MinioConfig__Username: user
      MinioConfig__Password: password
      MinioConfig__Endpoint: dotnet_minio
      MinioConfig__Port: 9000
      MinioConfig__WithSsl: false
    depends_on:
      - dotnet_minio

volumes:
  postgres_data:

networks:
  dotnet_network: